### ISSUE TITLE
Memcached TaggablePoolInterface expected MemcachedCachePool given

### ISSUE THREAD

**Issue by PaddyLock** [php-cache/issues#50] opened 2016-03-24 10:51 UTC
When I try to clear the cache using `app/console cache:flush all` I get the following warning:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'

In the following method in Cache\CacheBundle\CommandCacheFlushCommand

```
private function clearTypedCacheFromService($type, $serviceId)
    {
        /** @type \Psr\Cache\CacheItemPoolInterface $service */
        $service = $this->getContainer()->get($serviceId);
        if ($service instanceof TaggablePoolInterface) {
            return $service->clearTags([$type]);
        } else {
            return $service->clear();
        }
    }
```

Cache\Adapter\Memcached\MemcachedCachePool does not implement TaggablePoolInterface. However, in Cache\CacheBundle\Command\CacheFlushCommand -> clearTypedCacheFromService() the service IS an instance of TaggablePoolInterface although when I dump $service here I get

Cache\CacheBundle\Cache\RecordingCachePool {#450
  -calls: []
  -cachePool: Cache\Adapter\Memcached\MemcachedCachePool {#446
    -cache: Memcached {#449}
    #deferred: []
    -keyCache: []
  }
}

If I temporarily return $service->clear(); then I can get the cache to clear. However, after returning the code to it's original state and then running my web application, I then get the following:

`Argument 1 passed to Cache\CacheBundle\Cache\FixedTaggingCachePool::__construct() must be an instance of Cache\Taggable\TaggablePoolInterface, instance of Cache\Adapter\Memcached\MemcachedCachePool given, called in /***********/vendor/cache/cache-bundle/src/Factory/DoctrineBridgeFactory.php on line 33 and defined', '/*******/vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php', '41', array()) in FixedTaggingCachePool.php line 41`

I'm not sure why tagging is a requirement anyway, as I am not using tagging myself.

**Comment by PaddyLock** [comment] 2016-03-24 11:20
I think the solution is that `Cache\Adapter\Memcached\MemcachedCachePool` needs to `implements TaggablePoolInterface` ?

and then implement clearTags()

However, I am not sure what needs to be in clearTags()

Is this something that will be in a coming release?

I have hacked this file locally and it seems to work with an empty clearTags method, as I am not using tags.

**Comment by Nyholm** [comment] 2016-03-24 12:21
Thank you for this detailed bug report. 
It seams like there is an issue with the RecordignCachePool. It is always an instance of TaggablePoolInterface and that is why the check always validates to true.. I will investigate further to find a solution.

**Comment by PaddyLock** [comment] 2016-03-24 13:07
As a bit of extra info these are the packages I have

        ```
        "cache/doctrine-adapter": "0.5.*",
        "cache/psr-6-doctrine-bridge": "2.1.*",
        "cache/cache-bundle": "dev-normalizer",
        "cache/adapter-bundle": "0.3.*",
        "cache/memcached-adapter": "dev-master",
        "cache/taggable-cache": "0.4.*",
        "cache/hierarchical-cache": "0.2.1",
        "cache/adapter-common": "0.3.0"
```

**Comment by morgangiraud** [comment] 2016-03-29 14:38
This is a bigger problem.
Since the last packagist upgrade (in my case):
- cache/adapter-bundle: 0.3.2 -> 0.3.3
- cache/adapter-common: 0.2.1 -> 0.3.0
- cache/hierarchical-cache: 0.2.0 -> 0.2.1
- cache/memcached-adapter: 0.2.0 -> 0.3.1
- cache/taggable-cache: 0.3.1 -> 0.4.0

It also broke a completely unrelated commands (assets:dump from assetic) due to the doctrineBridge getting loaded.

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Cache\CacheBundle\Cache\FixedTaggingCachePool::__construct()
must be an instance of Cache\Taggable\TaggablePoolInterface,
instance of Cache\Adapter\Memcached\MemcachedCachePool given, 
called in vendor/cache/cache-bundle/src/Factory/DoctrineBridgeFactory.php on line 33 
and defined in vendor/cache/cache-bundle/src/Cache/FixedTaggingCachePool.php:41
```

Hope it will helps you solve this deps problems, seems definitely like someone is not implementing the right interface.

**Comment by Nyholm** [comment] 2016-03-29 14:44
Have you tried the fix in the linked PR?
https://github.com/php-cache/cache-bundle/pull/57

**Comment by morgangiraud** [comment] 2016-03-29 15:26
Cool, my deployment script and my app is working again in preproduction (should be allright in production).

Thanks, that was fast!

**Comment by ajtis** [comment] 2016-06-11 11:14
Try to create cache pool (chain)
```
cache_adapter:
    providers:
        my_memcached:
            factory: 'cache.factory.memcached'
            aliases: ['cache.memcached']
            options:
                host: 172.17.0.3 # Using custom host
                port: 11211
        my_chain:
            factory: 'cache.factory.chain'
            options:
                services:
                    - @cache.provider.my_memcached
cache:
    doctrine:
        enabled: true
        metadata:
            service_id: 'cache.provider.my_chain'
            entity_managers:   [ default ]       # the name of your entity_manager connection
            document_managers: [ default ]       # the name of your document_manager connection
        result:
            service_id: 'cache.provider.my_chain'
            entity_managers:   [ default, read ] # you may specify multiple entity_managers
        query:
            service_id: 'cache.provider.my_chain'
            entity_managers: [ default ]
```

composer includes:
```

        "cache/cache-bundle": "^0.4.1",
        "cache/adapter-bundle": "^0.3.3",
        "cache/psr-6-doctrine-bridge": "^2.1",
        "cache/memcached-adapter": "^0.3.1"
```

**Comment by jewome62** [comment] 2016-07-26 09:56
I have the same problem.
Do you have solution for this ?

```
 Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags' 
```

I use last tags version

**Comment by Nyholm** [comment] 2016-08-07 15:21
Fixed by https://github.com/php-cache/cache-bundle/pull/57

I'll make sure to tag a new version of the bundle within a couple of minutes.

**Closed by Nyholm** 2016-08-07 15:21 UTC

**Comment by jewome62** [comment] 2016-09-14 13:34
Hi,

I have always same problem with last tag

```bash
root@openvoice:/var/www/project# app/console cache:flush all
                                                                                                                                                                     
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                          
  Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Memcached\MemcachedCachePool' does not have a method 'clearTags'  
                                                                                                                                                                     

cache:flush [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<type>] [<service>]

```

composer.json
```json
    "cache/cache-bundle": "^0.4",
    "cache/adapter-bundle": "^0.3",
    "cache/psr-6-doctrine-bridge": "^2.1",
    "cache/memcached-adapter": "^0.3",
    "cache/apc-adapter": "^0.3",
    "cache/array-adapter": "^0.4"
```

composer show
```bash
cache/adapter-bundle                 0.3.5              A bundle that registers cache implementations as Symfony services supporting PSR-6 and tagging
cache/adapter-common                 0.3.3              Common classes for PSR-6 adapters
cache/apc-adapter                    0.3.2              A PSR-6 cache implementation using apc. This implementation supports tags
cache/array-adapter                  0.4.2              A PSR-6 cache implementation using a php array. This implementation supports tags
cache/cache-bundle                   0.4.4              Symfony 2 bundle providing integration between PSR-6 compliant cache services and the framework. It supports...
cache/hierarchical-cache             0.3.0              A helper trait and interface to your PSR-6 cache to support hierarchical keys.
cache/memcached-adapter              0.3.2              A PSR-6 cache implementation using Memcached. This implementation supports tags
cache/namespaced-cache               0.1.1              A decorator that makes your cache support namespaces
cache/psr-6-doctrine-bridge          2.2.0              PSR-6 Doctrine bridge
cache/session-handler                0.1.0              An implementation of PHP's SessionHandlerInterface that allows PSR-6
cache/taggable-cache                 0.4.3              Add tag support to your PSR-6 cache implementation
```

**Comment by tburschka** [comment] 2016-09-29 06:48
Same here

output
                                                                                                          
      [Symfony\Component\Debug\Exception\ContextErrorException]                                                
      Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Cache\Adapter\Apcu\ApcuCachePool' does not have a method 'clearTags'                                                         

Trace

     () at /var/www/vendor/cache/cache-bundle/src/Cache/Recording/CachePool.php:83
     Symfony\Component\Debug\ErrorHandler->handleError() at n/a:n/a
     call_user_func_array() at /var/www/vendor/cache/cache-bundle/src/Cache/Recording/CachePool.php:83
     Cache\CacheBundle\Cache\Recording\CachePool->timeCall() at /var/www/vendor/cache/cache-bundle/src/Cache/Recording/CachePool.php:169
     Cache\CacheBundle\Cache\Recording\CachePool->clearTags() at /var/www/vendor/cache/cache-bundle/src/Command/CacheFlushCommand.php:126
     Cache\CacheBundle\Command\CacheFlushCommand->clearTypedCacheFromService() at /var/www/vendor/cache/cache-bundle/src/Command/CacheFlushCommand.php:111
     Cache\CacheBundle\Command\CacheFlushCommand->clearCacheForBuiltInType() at /var/ww/vendor/cache/cache-bundle/src/Command/CacheFlushCommand.php:80
     Cache\CacheBundle\Command\CacheFlushCommand->execute() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:256
     Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:834
     Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:186
     Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
     Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:117
     Symfony\Component\Console\Application->run() at /var/www/bin/console:29



composer.json
                                                        
    "cache/cache-bundle": "^0.4",
    "cache/adapter-bundle": "^0.4",
    "cache/redis-adapter": "^0.4",
    "cache/apcu-adapter": "^0.2",
    "cache/psr-6-doctrine-bridge": "^2.2"

composer show

    cache/adapter-bundle                    0.4.0              A bundle that registers cache implementation...
    cache/adapter-common                    0.3.3              Common classes for PSR-6 adapters
    cache/apcu-adapter                      0.2.2              A PSR-6 cache implementation using apcu. Thi...
    cache/cache-bundle                      0.4.4              Symfony 2 bundle providing integration betwe...
    cache/hierarchical-cache                0.3.0              A helper trait and interface to your PSR-6 c...
    cache/namespaced-cache                  0.1.1              A decorator that makes your cache support na...
    cache/psr-6-doctrine-bridge             2.2.0              PSR-6 Doctrine bridge
    cache/redis-adapter                     0.4.2              A PSR-6 cache implementation using Redis (Ph...
    cache/session-handler                   0.1.0              An implementation of PHP's SessionHandlerInt...
    cache/taggable-cache                    0.4.3              Add tag support to your PSR-6 cache implemen...

**Comment by jewome62** [comment] 2016-10-05 13:56
@Nyholm For resolve the bug, we use 0.4.3 of cache/cache-bundle
